blank_issues_enabled: false
contact_links:
  - name: ğŸ™Œ Beitragshinweise
    url: https://nyxb.nexus/contribute
    about: Bitte lies dies durch.
  - name: ğŸ“œ Verhaltenskodex
    url: https://nyxb.nexus/code-of-conduct
    about: Bitte lies dies durch.
  - name: â‰ï¸ Warum und Wie man eine Reproduktion erstellt?
    url: https://nyxb.nexus/posts/why-reproductions-are-required
    about: Eine Reproduktion ist sehr wichtig, falls nur du das problem hast mÃ¼ssen wir es rekonstruieren!
